# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weldsentry_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 797)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1040, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/mcfly/.designer/backup/runs/detect/exp/patches_5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_global = QtWidgets.QFrame(self.centralwidget)
        self.frame_global.setStyleSheet("background-color: #0061FE;")
        self.frame_global.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_global.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_global.setObjectName("frame_global")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_global)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_head = QtWidgets.QLabel(self.frame_global)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_head.sizePolicy().hasHeightForWidth())
        self.label_head.setSizePolicy(sizePolicy)
        self.label_head.setMinimumSize(QtCore.QSize(0, 75))
        self.label_head.setMaximumSize(QtCore.QSize(16777215, 75))
        self.label_head.setStyleSheet("\n"
"#label_head {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 32px;\n"
"padding-left: 36px;\n"
"padding-top: -8px;\n"
"    color: white;\n"
"    background-color: #0061FE;\n"
"}\n"
"\n"
"")
        self.label_head.setObjectName("label_head")
        self.verticalLayout_2.addWidget(self.label_head)
        self.tab = QtWidgets.QTabWidget(self.frame_global)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMinimumSize(QtCore.QSize(0, 75))
        self.tab.setMaximumSize(QtCore.QSize(16777215, 75))
        self.tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tab.setStyleSheet("/* 设置标签页的背景颜色 */\n"
"    QTabWidget {\n"
"        background-color: #A7C6FF;\n"
"             \n"
"    }\n"
"    \n"
"    /* 设置标签页的选中状态下的背景颜色 */\n"
"    QTabWidget::pane {\n"
"        border-top: 2px solid #74A7FF;\n"
"        background-color: #74A7FF;\n"
"\n"
"    }\n"
"    \n"
"    \n"
"\n"
"    /* 设置标签页按钮的初始颜色 */\n"
"    QTabBar::tab {\n"
"        background-color: #A7C6FF;\n"
"        border: 2px solid #A7C6FF;\n"
"        border-bottom-color: #A7C6FF;\n"
"        border-top-left-radius: 8px;\n"
"        border-top-right-radius: 8px;\n"
"        min-width: 0;\n"
"        padding: 6px;\n"
"        margin-right: 10px; /* 调整按钮间的间隔 */\n"
"        width: 150%;\n"
"                font-family: \"Microsoft YaHei\";\n"
"        font: 15px;\n"
"    }\n"
"    \n"
"    /* 设置标签页按钮的选中颜色 */\n"
"    QTabBar::tab:selected, QTabBar::tab:hover {\n"
"        background-color: #74A7FF;\n"
"        border-color: #74A7FF;\n"
"    }\n"
"    \n"
"    /* 设置标签页下面区域的背景颜色 */\n"
"   QWidget#tab_1, QWidget#tab_3, QWidget#tab_2, QWidget#tab_4 {\n"
"        background-color: #74A7FF;\n"
"    }")
        self.tab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab.setElideMode(QtCore.Qt.ElideNone)
        self.tab.setDocumentMode(False)
        self.tab.setMovable(False)
        self.tab.setTabBarAutoHide(False)
        self.tab.setObjectName("tab")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_auto = QtWidgets.QFrame(self.tab_1)
        self.frame_auto.setStyleSheet("background-color: #74A7FF")
        self.frame_auto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_auto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_auto.setObjectName("frame_auto")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_auto)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_auto)
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_auto)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.frame_6 = QtWidgets.QFrame(self.frame_auto)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_auto)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_auto)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_auto)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_auto)
        self.tab.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_histo = QtWidgets.QFrame(self.tab_3)
        self.frame_histo.setStyleSheet("background-color: #74A7FF")
        self.frame_histo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_histo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_histo.setObjectName("frame_histo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_histo)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_his1 = QtWidgets.QPushButton(self.frame_histo)
        self.btn_his1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_his1.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_his1.setObjectName("btn_his1")
        self.horizontalLayout_3.addWidget(self.btn_his1)
        self.btn_his_defect = QtWidgets.QPushButton(self.frame_histo)
        self.btn_his_defect.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_his_defect.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_his_defect.setObjectName("btn_his_defect")
        self.horizontalLayout_3.addWidget(self.btn_his_defect)
        self.btn_his2 = QtWidgets.QPushButton(self.frame_histo)
        self.btn_his2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_his2.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_his2.setObjectName("btn_his2")
        self.horizontalLayout_3.addWidget(self.btn_his2)
        self.frm1 = QtWidgets.QFrame(self.frame_histo)
        self.frm1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm1.setObjectName("frm1")
        self.horizontalLayout_3.addWidget(self.frm1)
        self.frm2 = QtWidgets.QFrame(self.frame_histo)
        self.frm2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm2.setObjectName("frm2")
        self.horizontalLayout_3.addWidget(self.frm2)
        self.frm3 = QtWidgets.QFrame(self.frame_histo)
        self.frm3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm3.setObjectName("frm3")
        self.horizontalLayout_3.addWidget(self.frm3)
        self.horizontalLayout_4.addWidget(self.frame_histo)
        self.tab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_6.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_asst = QtWidgets.QFrame(self.tab_4)
        self.frame_asst.setStyleSheet("background-color: #74A7FF")
        self.frame_asst.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_asst.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_asst.setObjectName("frame_asst")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_asst)
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_ast1 = QtWidgets.QPushButton(self.frame_asst)
        self.btn_ast1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_ast1.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_ast1.setObjectName("btn_ast1")
        self.horizontalLayout_5.addWidget(self.btn_ast1)
        self.btn_ast2 = QtWidgets.QPushButton(self.frame_asst)
        self.btn_ast2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_ast2.setStyleSheet("QPushButton {\n"
"        background-color: #A7C6FF;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 1px; /* 无圆角 */\n"
"        border-top-color: white ;\n"
"border-left-color: white ;\n"
"border-right-color: black; \n"
"border-bottom-color: black; \n"
"        font:  12px;\n"
"        min-width: 0; /* 允许按钮宽度自适应 */\n"
"\n"
"        padding: 6px;\n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed {\n"
"        background-color: #74A7FF;\n"
"        border-style: none;\n"
"    }\n"
"\n"
" /* 鼠标悬停时的样式 */\n"
"    QPushButton:hover {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_ast2.setObjectName("btn_ast2")
        self.horizontalLayout_5.addWidget(self.btn_ast2)
        self.frm_ast1 = QtWidgets.QFrame(self.frame_asst)
        self.frm_ast1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_ast1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_ast1.setObjectName("frm_ast1")
        self.horizontalLayout_5.addWidget(self.frm_ast1)
        self.frm_ast2 = QtWidgets.QFrame(self.frame_asst)
        self.frm_ast2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_ast2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_ast2.setObjectName("frm_ast2")
        self.horizontalLayout_5.addWidget(self.frm_ast2)
        self.frm_ast3 = QtWidgets.QFrame(self.frame_asst)
        self.frm_ast3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_ast3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_ast3.setObjectName("frm_ast3")
        self.horizontalLayout_5.addWidget(self.frm_ast3)
        self.frm_ast4 = QtWidgets.QFrame(self.frame_asst)
        self.frm_ast4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_ast4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_ast4.setObjectName("frm_ast4")
        self.horizontalLayout_5.addWidget(self.frm_ast4)
        self.horizontalLayout_6.addWidget(self.frame_asst)
        self.tab.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tab)
        self.frame_main = QtWidgets.QFrame(self.frame_global)
        self.frame_main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main.sizePolicy().hasHeightForWidth())
        self.frame_main.setSizePolicy(sizePolicy)
        self.frame_main.setStyleSheet("background-color: white;")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setLineWidth(1)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout_7.setContentsMargins(0, 6, 6, 6)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_console = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_console.sizePolicy().hasHeightForWidth())
        self.frame_console.setSizePolicy(sizePolicy)
        self.frame_console.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_console.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_console.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_console.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_console.setObjectName("frame_console")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_console)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setSpacing(0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.label_ic = QtWidgets.QLabel(self.frame_console)
        self.label_ic.setMinimumSize(QtCore.QSize(80, 84))
        self.label_ic.setStyleSheet("#label_ic {\n"
"        background-color: gray;\n"
"        width: 80px;\n"
"        height: 80px;\n"
"        border-radius: 40px;\n"
"\n"
"}")
        self.label_ic.setText("")
        self.label_ic.setObjectName("label_ic")
        self.gridLayout_1.addWidget(self.label_ic, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_1.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_1.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_1.addItem(spacerItem2, 1, 0, 1, 1)
        self.label_auth_stat = QtWidgets.QLabel(self.frame_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_auth_stat.sizePolicy().hasHeightForWidth())
        self.label_auth_stat.setSizePolicy(sizePolicy)
        self.label_auth_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_auth_stat.setObjectName("label_auth_stat")
        self.gridLayout_1.addWidget(self.label_auth_stat, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_1.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_1.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_1.addItem(spacerItem5, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_console)
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 200))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_8.addWidget(self.textBrowser)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem8, 3, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 2, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 2, 0, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(120, 60))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(120, 60))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_start = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_start.setStyleSheet("QPushButton {\n"
"        background-color: #0061FE;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 4px; \n"
"        /* 边界 **/\n"
"        border-top-color: white ;\n"
"        border-left-color: white ;\n"
"        border-right-color: black; \n"
"        border-bottom-color: black; \n"
"        \n"
"        color: white;\n"
"        font: bold 20px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"        \n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed  {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_12.addWidget(self.btn_start)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_pause = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pause.sizePolicy().hasHeightForWidth())
        self.btn_pause.setSizePolicy(sizePolicy)
        self.btn_pause.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_pause.setStyleSheet("QPushButton {\n"
"        background-color: brown;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 4px; \n"
"        /* 边界 **/\n"
"        border-top-color: white ;\n"
"        border-left-color: white ;\n"
"        border-right-color: black; \n"
"        border-bottom-color: black; \n"
"        \n"
"        color: white;\n"
"        font: bold 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"        \n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed  {\n"
"        background-color: #da7171; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout_13.addWidget(self.btn_pause)
        self.stackedWidget_2.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_7.addWidget(self.frame_console)
        self.frame_sep1 = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sep1.sizePolicy().hasHeightForWidth())
        self.frame_sep1.setSizePolicy(sizePolicy)
        self.frame_sep1.setMinimumSize(QtCore.QSize(0, 600))
        self.frame_sep1.setMaximumSize(QtCore.QSize(16777215, 161561))
        self.frame_sep1.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_sep1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sep1.setObjectName("frame_sep1")
        self.horizontalLayout_7.addWidget(self.frame_sep1)
        self.frame_im = QtWidgets.QFrame(self.frame_main)
        self.frame_im.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_im.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_im.setObjectName("frame_im")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_im)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_im)
        self.stackedWidget.setStyleSheet("QLabel {\n"
"     font-family: \"Microsoft YaHei\";\n"
"    font: 14px;\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_input = QtWidgets.QWidget()
        self.page_input.setObjectName("page_input")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_input)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(3, 10, 3, 3)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setVerticalSpacing(20)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lb1 = QtWidgets.QLabel(self.page_input)
        self.lb1.setObjectName("lb1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb1)
        self.lb2 = QtWidgets.QLabel(self.page_input)
        self.lb2.setObjectName("lb2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb2)
        self.lb4 = QtWidgets.QLabel(self.page_input)
        self.lb4.setObjectName("lb4")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb4)
        self.le1 = QtWidgets.QLineEdit(self.page_input)
        self.le1.setObjectName("le1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le1)
        self.le2 = QtWidgets.QLineEdit(self.page_input)
        self.le2.setObjectName("le2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le2)
        self.frm_photo = QtWidgets.QFrame(self.page_input)
        self.frm_photo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_photo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_photo.setObjectName("frm_photo")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frm_photo)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.le4 = QtWidgets.QLineEdit(self.frm_photo)
        self.le4.setObjectName("le4")
        self.horizontalLayout_9.addWidget(self.le4)
        self.btn_photo = QtWidgets.QPushButton(self.frm_photo)
        self.btn_photo.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_photo.setStyleSheet("QPushButton {\n"
"        background-color: #0061FE;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 4px; \n"
"        /* 边界 **/\n"
"        border-top-color: white ;\n"
"        border-left-color: white ;\n"
"        border-right-color: black; \n"
"        border-bottom-color: black; \n"
"        \n"
"        color: white;\n"
"        font:  9px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"        \n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed  {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_photo.setObjectName("btn_photo")
        self.horizontalLayout_9.addWidget(self.btn_photo)
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frm_photo)
        self.lb0 = QtWidgets.QLabel(self.page_input)
        self.lb0.setObjectName("lb0")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb0)
        self.lb3 = QtWidgets.QLabel(self.page_input)
        self.lb3.setObjectName("lb3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb3)
        self.le3 = QtWidgets.QLineEdit(self.page_input)
        self.le3.setObjectName("le3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le3)
        self.frm_photo2 = QtWidgets.QFrame(self.page_input)
        self.frm_photo2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_photo2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_photo2.setObjectName("frm_photo2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frm_photo2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.le5 = QtWidgets.QLineEdit(self.frm_photo2)
        self.le5.setObjectName("le5")
        self.horizontalLayout_11.addWidget(self.le5)
        self.btn_photo2 = QtWidgets.QPushButton(self.frm_photo2)
        self.btn_photo2.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_photo2.setStyleSheet("QPushButton {\n"
"        background-color: #0061FE;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 4px; \n"
"        /* 边界 **/\n"
"        border-top-color: white ;\n"
"        border-left-color: white ;\n"
"        border-right-color: black; \n"
"        border-bottom-color: black; \n"
"        \n"
"        color: white;\n"
"        font:  9px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"        \n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed  {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_photo2.setObjectName("btn_photo2")
        self.horizontalLayout_11.addWidget(self.btn_photo2)
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frm_photo2)
        self.lb5 = QtWidgets.QLabel(self.page_input)
        self.lb5.setObjectName("lb5")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lb5)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.frame_18 = QtWidgets.QFrame(self.page_input)
        self.frame_18.setMinimumSize(QtCore.QSize(100, 20))
        self.frame_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_18.setLineWidth(1)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_5.addWidget(self.frame_18)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(3, -1, 3, 3)
        self.formLayout_2.setHorizontalSpacing(10)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lb_para0 = QtWidgets.QLabel(self.page_input)
        self.lb_para0.setObjectName("lb_para0")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_para0)
        self.lb_para1 = QtWidgets.QLabel(self.page_input)
        self.lb_para1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_para1.setObjectName("lb_para1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_para1)
        self.lb_para2 = QtWidgets.QLabel(self.page_input)
        self.lb_para2.setObjectName("lb_para2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_para2)
        self.le_para2 = QtWidgets.QLineEdit(self.page_input)
        self.le_para2.setObjectName("le_para2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_para2)
        self.le_para1 = QtWidgets.QLineEdit(self.page_input)
        self.le_para1.setObjectName("le_para1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_para1)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.btn_confirm = QtWidgets.QPushButton(self.page_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_confirm.sizePolicy().hasHeightForWidth())
        self.btn_confirm.setSizePolicy(sizePolicy)
        self.btn_confirm.setMinimumSize(QtCore.QSize(60, 25))
        self.btn_confirm.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_confirm.setStyleSheet("QPushButton {\n"
"        background-color: #0061FE;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 4px; \n"
"        /* 边界 **/\n"
"        border-top-color: white ;\n"
"        border-left-color: white ;\n"
"        border-right-color: black; \n"
"        border-bottom-color: black; \n"
"        \n"
"        color: white;\n"
"        font:  12px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"        \n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed  {\n"
"        background-color: #A7C6FF; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_10.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(self.page_input)
        self.btn_cancel.setMinimumSize(QtCore.QSize(60, 25))
        self.btn_cancel.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"        background-color: silver;\n"
"           border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 4px; \n"
"        /* 边界 **/\n"
"        border-top-color: white ;\n"
"        border-left-color: white ;\n"
"        border-right-color: black; \n"
"        border-bottom-color: black; \n"
"        \n"
"        color: white;\n"
"        font: 12px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"        \n"
"    }\n"
"/* 鼠标点击时的样式 */\n"
"QPushButton:pressed  {\n"
"        background-color: lightgray; /* 悬停时的背景颜色 */\n"
"        position: relative; /* 相对定位 */\n"
"        left: -2px; /* 向左轻微移动 */\n"
"        top: -2px; /* 向上轻微移动 */\n"
"        /* 通过改变left和top值模拟抖动效果 */\n"
"    }\n"
"\n"
"    ")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_10.addWidget(self.btn_cancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.page_input)
        self.page_show = QtWidgets.QWidget()
        self.page_show.setObjectName("page_show")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.page_show)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lb_show = QtWidgets.QLabel(self.page_show)
        self.lb_show.setText("")
        self.lb_show.setObjectName("lb_show")
        self.horizontalLayout_14.addWidget(self.lb_show)
        self.frame = QtWidgets.QFrame(self.page_show)
        self.frame.setMinimumSize(QtCore.QSize(31, 0))
        self.frame.setMaximumSize(QtCore.QSize(31, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_close = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(30, 20))
        self.btn_close.setStyleSheet("QPushButton#btn_close {\n"
"    background-color: #e81123; /* Windows 10 红色 */\n"
"    border: none;\n"
"    border-radius: 3px; /* 圆角大小 */\n"
"    color: white; /* “X”图标的颜色 */\n"
"    font-size: 16px; /* 图标大小 */\n"
"    font-weight: bold;\n"
"    padding: 2px; /* 内边距 */\n"
"    text-align: center; /* 文本居中 */\n"
"    width: 20px; /* 按钮宽度 */\n"
"    height: 20px; /* 按钮高度 */\n"
"    outline: none; /* 移除焦点时的轮廓线 */\n"
"}\n"
"\n"
"QPushButton#btn_close:hover {\n"
"    background-color: #f1707a; /* 鼠标悬停时的颜色 */\n"
"}\n"
"\n"
"QPushButton#btn_close:pressed {\n"
"    background-color: #d20f2a; /* 按钮按下时的颜色 */\n"
"}\n"
"")
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_7.addWidget(self.btn_close)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_14.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_show)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.frame_19 = QtWidgets.QFrame(self.frame_im)
        self.frame_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_4.addWidget(self.frame_19)
        self.terminal = QtWidgets.QTextBrowser(self.frame_im)
        self.terminal.setObjectName("terminal")
        self.verticalLayout_4.addWidget(self.terminal)
        self.horizontalLayout_7.addWidget(self.frame_im)
        self.frame_sep2 = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sep2.sizePolicy().hasHeightForWidth())
        self.frame_sep2.setSizePolicy(sizePolicy)
        self.frame_sep2.setMinimumSize(QtCore.QSize(0, 600))
        self.frame_sep2.setMaximumSize(QtCore.QSize(16777215, 161561))
        self.frame_sep2.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_sep2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sep2.setObjectName("frame_sep2")
        self.horizontalLayout_7.addWidget(self.frame_sep2)
        self.frame_xls = QtWidgets.QFrame(self.frame_main)
        self.frame_xls.setMinimumSize(QtCore.QSize(360, 0))
        self.frame_xls.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_xls.setStyleSheet("background-color: mistyrose ;")
        self.frame_xls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_xls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_xls.setObjectName("frame_xls")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_xls)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tb_bc = QtWidgets.QTableWidget(self.frame_xls)
        self.tb_bc.setStyleSheet("QTableWidget {\n"
"        gridline-color: black;\n"
"        font-family: \"Microsoft Yahei\";\n"
"    }\n"
"    QTableWidget::item:hover {\n"
"        background-color: #0061FE;\n"
"    }\n"
"    QTableWidget QTableCornerButton::section {\n"
"        background: transparent;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: white;\n"
"    }\n"
"\n"
"\n"
"\n"
"")
        self.tb_bc.setCornerButtonEnabled(True)
        self.tb_bc.setObjectName("tb_bc")
        self.tb_bc.setColumnCount(7)
        self.tb_bc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_bc.setHorizontalHeaderItem(6, item)
        self.tb_bc.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tb_bc)
        self.tb_detail = QtWidgets.QTableWidget(self.frame_xls)
        self.tb_detail.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tb_detail.setStyleSheet("QTableWidget {\n"
"        gridline-color: black;\n"
"        font-family: \"Microsoft Yahei\";\n"
"    }\n"
"    QTableWidget::item:hover {\n"
"        background-color: #0061FE;\n"
"    }\n"
"    QTableWidget QTableCornerButton::section {\n"
"        background: transparent;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: white;\n"
"    }\n"
"\n"
"\n"
"\n"
"")
        self.tb_detail.setObjectName("tb_detail")
        self.tb_detail.setColumnCount(4)
        self.tb_detail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_detail.setHorizontalHeaderItem(3, item)
        self.tb_detail.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tb_detail)
        self.horizontalLayout_7.addWidget(self.frame_xls)
        self.verticalLayout_2.addWidget(self.frame_main)
        self.label_head.raise_()
        self.frame_main.raise_()
        self.tab.raise_()
        self.verticalLayout.addWidget(self.frame_global)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WeldSentry"))
        self.label_head.setText(_translate("MainWindow", "大型金属焊接接口缺陷检测系统"))
        self.pushButton_2.setText(_translate("MainWindow", "授权密钥查看"))
        self.pushButton.setText(_translate("MainWindow", "授权密钥验证"))
        self.tab.setTabText(self.tab.indexOf(self.tab_1), _translate("MainWindow", "授权管理"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("MainWindow", "缺陷检测"))
        self.btn_his1.setText(_translate("MainWindow", "历史数据查看"))
        self.btn_his_defect.setText(_translate("MainWindow", "不合格品信息查看"))
        self.btn_his2.setText(_translate("MainWindow", "历史趋势预测"))
        self.tab.setTabText(self.tab.indexOf(self.tab_3), _translate("MainWindow", "历史数据"))
        self.btn_ast1.setText(_translate("MainWindow", "使用手册"))
        self.btn_ast2.setText(_translate("MainWindow", "联系电话"))
        self.tab.setTabText(self.tab.indexOf(self.tab_4), _translate("MainWindow", "技术支持"))
        self.label_auth_stat.setText(_translate("MainWindow", "Temp"))
        self.btn_start.setText(_translate("MainWindow", "开始"))
        self.btn_pause.setText(_translate("MainWindow", "暂停/结束"))
        self.lb1.setText(_translate("MainWindow", "生产批次号"))
        self.lb2.setText(_translate("MainWindow", "负责人"))
        self.lb4.setText(_translate("MainWindow", "检测路径"))
        self.btn_photo.setText(_translate("MainWindow", "选择"))
        self.lb0.setText(_translate("MainWindow", "信息"))
        self.lb3.setText(_translate("MainWindow", "型号"))
        self.btn_photo2.setText(_translate("MainWindow", "选择"))
        self.lb5.setText(_translate("MainWindow", "结果路径"))
        self.lb_para0.setText(_translate("MainWindow", "参数"))
        self.lb_para1.setText(_translate("MainWindow", "参数1"))
        self.lb_para2.setText(_translate("MainWindow", "参数2"))
        self.btn_confirm.setText(_translate("MainWindow", "确认"))
        self.btn_cancel.setText(_translate("MainWindow", "取消"))
        self.btn_close.setText(_translate("MainWindow", "×"))
        item = self.tb_bc.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tb_bc.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "型号"))
        item = self.tb_bc.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "生产批次号"))
        item = self.tb_bc.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "负责人"))
        item = self.tb_bc.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "图像"))
        item = self.tb_bc.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "检测时间"))
        item = self.tb_bc.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "是否合格"))
        item = self.tb_detail.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tb_detail.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "图像"))
        item = self.tb_detail.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "缺陷类型"))
        item = self.tb_detail.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "详细信息"))
